export const memes=['memes','holup','comedyhomicide','cursedcomments','murderedbywords']
export const nature=['EarthPorn','natureporn','NatureIsFuckingLit']
export const funny=['funny']
export const art=['drawing','art']
export const others=['coolguides','pics','wholesomememes','perfecttiming']