export const memes=['memes','holup','cursedcomments','murderedbywords','dankmemes']
export const nature=['EarthPorn','natureporn','NatureIsFuckingLit']
export const funny=['funny','comics','webcomics','lol']
export const art=['drawing','art','illustration','tattoos']
export const others=['coolguides','pics','wholesomememes','perfecttiming']